<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Docs Controller
 * File $file
 */
class DocsController extends AppController
{
    public string $fileName;

    /**
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->fileName = ROOT . '/documentation/HackYeah/pdfSourceADOC.pdf';
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        return $this->response
            ->withHeader('Content-Type', 'application/pdf')
            ->withFile($this->fileName, ['download' => false, 'name' => 'APIDokumentacja']);
    }
}
